'use client';

export default function Footer() {
  return (
    <footer className="mt-16 border-t border-slate-200 py-8 text-center">
      <p className="text-slate-500 text-sm">Generated by Interactive Canvas | Strategic Market Research</p>
    </footer>
  );
}
